-- MySQL Script generated by MySQL Workbench
-- Sun 07 Mar 2021 02:08:08 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lattics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lattics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lattics` ;
USE `lattics` ;

-- -----------------------------------------------------
-- Table `lattics`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lattics`.`organization` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `owner_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_organization_user1_idx` (`owner_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_organization_user1`
    FOREIGN KEY (`owner_user_id`)
    REFERENCES `lattics`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lattics`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lattics`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lattics`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lattics`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `active` VARCHAR(45) NULL,
  `organization_id` INT NULL,
  `role_id` INT NOT NULL,
  `avatar_URL` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_organization1_idx` (`organization_id` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `lattics`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `lattics`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lattics`.`simulation_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lattics`.`simulation_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lattics`.`simulation_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lattics`.`simulation_batch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_datetime` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `end_datetime` DATETIME NULL,
  `simulation_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_simulation_batch_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_simulation_batch_simulation_status1_idx` (`simulation_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_simulation_batch_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lattics`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_simulation_batch_simulation_status1`
    FOREIGN KEY (`simulation_status_id`)
    REFERENCES `lattics`.`simulation_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lattics`.`simulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lattics`.`simulation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sequentialId` INT NOT NULL,
  `created_datetime` DATETIME NULL,
  `start_datetime` DATETIME NULL,
  `end_datetime` VARCHAR(45) NULL,
  `simulation_batch_id` INT NULL,
  `status_simulation_id` INT NOT NULL,
  `input_data_url` VARCHAR(45) NULL,
  `output_data_url` VARCHAR(45) NULL,
  `owner` INT NULL,
  `finished_percentage` INT NULL,
  INDEX `fk_simulation_simulation_batch_idx` (`simulation_batch_id` ASC) VISIBLE,
  INDEX `fk_simulation_status_simulation1_idx` (`status_simulation_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_simulation_user1_idx` (`owner` ASC) VISIBLE,
  UNIQUE INDEX `unique_sequenctial` (`owner` ASC, `sequentialId` ASC) VISIBLE,
  CONSTRAINT `fk_simulation_simulation_batch`
    FOREIGN KEY (`simulation_batch_id`)
    REFERENCES `lattics`.`simulation_batch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_simulation_status_simulation1`
    FOREIGN KEY (`status_simulation_id`)
    REFERENCES `lattics`.`simulation_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_simulation_user1`
    FOREIGN KEY (`owner`)
    REFERENCES `lattics`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lattics`.`simulation_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lattics`.`simulation_result` (
  `id` INT NOT NULL,
  `simulation_id` INT NOT NULL,
  `result_documentURL` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_simulation_result_simulation1_idx` (`simulation_id` ASC) VISIBLE,
  CONSTRAINT `fk_simulation_result_simulation1`
    FOREIGN KEY (`simulation_id`)
    REFERENCES `lattics`.`simulation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lattics`.`tag_simulation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lattics`.`tag_simulation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `simulation_id` INT NOT NULL,
  `tag` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_simulation_simulation1_idx` (`simulation_id` ASC) VISIBLE,
  CONSTRAINT `fk_tag_simulation_simulation1`
    FOREIGN KEY (`simulation_id`)
    REFERENCES `lattics`.`simulation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
